import type { Metadata } from "next";

import "./globals.css";
import { rubik } from "@/components/font";
import { Footer, Navbar } from "@/components/ui";
import Providers from "@/components/providers/provider";

export const metadata: Metadata = {
  title:
    "Ecommerce - home to best electronics, gadgets and affordable accessories",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={rubik.className}>
        <Providers
        >
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
