import type { Metadata } from "next";

import { ThemeProvider } from "@/components/providers/theme-provider";
import "./globals.css";
import { rubik } from "@/components/font";
import { Footer, Navbar } from "@/components/ui";

export const metadata: Metadata = {
  title:
    "Ecommerce - home to best electronics, gadgets and affordable accessories",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={rubik.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          // enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
